{% set name = "nbqa" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ac0a5819c60307627e3917c15ceea856c4008592c6c0348560423b387aac066

build:
  number: 1
  noarch: python
  entry_points:
    - nbqa=nbqa.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.1
  run:
    - python >=3.6.1
    - toml
    - importlib_metadata # [py<38]

test:
  imports:
    - nbqa
  commands:
    - pip check
    - nbqa --help
  requires:
    - pip

about:
  home: https://github.com/nbQA-dev/nbQA
  summary: Run any Python code quality tool on a Jupyter Notebook!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
    - MarcoGorelli
    - girip11
