{% set name = "nbqa" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c63d9d1d56e53537efb42f019dac0c04938e9f940409920eb11780c458c9275

build:
  number: 0
  noarch: python
  entry_points:
    - nbqa=nbqa.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.1
  run:
    - python >=3.6.1
    - ipython >=7.8.0
    - toml
    # Only required for [py<38] but always include so this can be noarch: python
    - importlib_metadata

test:
  imports:
    - nbqa
  commands:
    - pip check
    - nbqa --help
  requires:
    - pip

about:
  home: https://github.com/nbQA-dev/nbQA
  summary: Run any Python code quality tool on a Jupyter Notebook!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
    - MarcoGorelli
    - girip11
