{% set name = "nbqa" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09e623f8a4b4c2aaf4ded94add0e3d731daabbf1b3d87b71ef5107acb9be0c43

build:
  number: 0
  noarch: python
  entry_points:
    - nbqa=nbqa.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.0
  run:
    - python >=3.7.0
    - ipython >=7.8.0
    - tomli
    - tokenize-rt >=3.2.0
    # Only required for [py<38] but always include so this can be noarch: python
    - importlib-metadata >=1.4

test:
  imports:
    - nbqa
  commands:
    - pip check
    - nbqa --help
  requires:
    - pip

about:
  home: https://github.com/nbQA-dev/nbQA
  summary: Run any Python code quality tool on a Jupyter Notebook!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
    - MarcoGorelli
    - girip11
